images_path: /home/simonexc/Documents/age-detect-app/data/train_data/
train_labels_path: /home/simonexc/Documents/age-detect-app/data/train_data/train.parquet
test_labels_path: /home/simonexc/Documents/age-detect-app/data/train_data/test.parquet
val_labels_path: /home/simonexc/Documents/age-detect-app/data/train_data/val.parquet

checkpoints_path: /home/simonexc/Documents/age-detect-app/data/checkpoints

auto_balance: true
epochs: 20
batch_size: 256
lr: 0.0001
drop: 0.2

noise_prob: 0.5
noise_std: 0.2

brightness: 0.5
contrast: 0.5
saturation: 0.5
hue: 0.5
